import csv

ATTRIBUTES_OUT = ".gitattributes"
FILTERS_OUT = ".gitconfig_filters"
CSV_FILE = "filters.csv"

gitattributes_lines = [
    "# Auto generated by generate_git_filters.py",
    "* text=auto",
    ""
]

filters_config_lines = [
    "# Auto generated by generate_git_filters.py",
    ""
]

with open(CSV_FILE, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        filename = row["filename"]
        filter_name = row["filter_name"]
        start_line = row["remove_from_line"]

        # gitattributes entry
        gitattributes_lines.append(f"{filename} filter={filter_name}")

        # git filter
        filters_config_lines.append(f'[filter "{filter_name}"]')
        filters_config_lines.append(f"    clean = sed '{start_line},$d'")
        filters_config_lines.append("    smudge = cat")
        filters_config_lines.append("")

# write .gitattributes
with open(ATTRIBUTES_OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(gitattributes_lines))

# write .gitconfig_filters
with open(FILTERS_OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(filters_config_lines))

print("Generated .gitattributes and .gitconfig_filters!")