site_name: My Docs
site_url: https://moita2025.github.io/
theme:
  name: material
  features:
    - content.code.copy
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite 
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/back_to_top.js
  - https://unpkg.com/twemoji@latest/dist/twemoji.min.js
  - https://unpkg.com/rough-notation/lib/rough-notation.iife.js

extra_css:
  - css/back_to_top.css

nav:
  - 首页: index.md
  - 编程:
      - Code_Programming/index.md
      - 网页开发:
          - Code_Programming/Web_Development/index.md
          - 自定义浏览器插件 DIYFilter:
              - 文件 1: Code_Programming/Web_Development/DIYFilter/s1-c1-f1-1.md
              - 文件 2: Code_Programming/Web_Development/DIYFilter/s1-c1-f1-2.md
          - Flask:
              - 文件 1: Code_Programming/Web_Development/Flask/s1-c1-f2-1.md
      - Python:
          - Code_Programming/Python/index.md
          - 文件处理:
              - 遍历查询后缀名: Code_Programming/Python/File_System/FileExtTraverse.md
          - 图像处理:
              - 随机噪声位图: Code_Programming/Python/Image/RandomNoise.md
      - Markdown:
          - RMD 标头: Code_Programming/Markdown/RmdHeader.md
  - 语言:
      - Languages/index.md
      - 托福:
          - Languages/TOEFL_iBT/index.md
          - 考试内容:  Languages/TOEFL_iBT/about.md